apiVersion: v1
kind: Service
metadata:
  name: route-planner
spec:
  type: NodePort
  selector:
    app: route-planner
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
